services:
  backend:
    build:
      context: ./app # ✅ Ensure this points to `app/`
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - UVICORN_WORKERS=2

  frontend:
    build:
      context: ./frontend
    ports:
      - "5500:80" # ✅ Maps local port 5500 to Nginx serving on port 80
    depends_on:
      - backend # ✅ Ensures the backend starts before the frontend
